---
- hosts: all
  become: true
  tasks:
    - name: Clone github repository
      git:
        repo: https://github.com/likheketo/ipo_filler
        dest: /home/ubuntu/ipo_filler
        clone: yes
        update: yes
    - name: Start ipo filler
      shell:
        cmd: "npm install && node main.js"
        chdir: /home/ubuntu/ipo_filler
